version: '3.8'
name: 'portfolio'
services:
  database:
    image: mysql:8.3.0
    container_name: mysql_portfolio
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - mysql-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin_portfolio
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    depends_on:
      - database

volumes:
  mysql-db:
    external: true